version: '3'
services:
  db:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/neo4j_test
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
  app:
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_URI=bolt://db:7687
      - DB_USER=neo4j
      - DB_PASSWORD=neo4j_test
